Repository koordinator-sh/charts, pull requests merged in 2022-09, with the labels that each got.

#42 add CoScheduling config to Charts
  versions/v0.7.0/templates/crd/scheduling.sigs.k8s.io_podgroups.yaml
  versions/v0.7.0/templates/koord-scheduler-config.yaml
  versions/v0.7.0/templates/rbac_role.yaml
Labels: lgtm, approved, size/L

#43 feature: add kubelet root-dir volume
  versions/v0.7.0/templates/koordlet.yaml
Labels: lgtm, size/XS, approved

#45 enable Reservation PreScore in koord-scheduler-config.yaml
  versions/v0.7.0/templates/koord-scheduler-config.yaml
Labels: lgtm, size/XS, approved

#46 change volume path to value
  versions/v0.7.0/templates/koordlet.yaml
  versions/v0.7.0/values.yaml
Labels: lgtm, approved, size/S

#47 add pods/eviction to koordlet
  versions/v0.7.0/templates/rbac_role.yaml
Labels: lgtm, size/XS, approved

#48 update v0.7.0 charts
  versions/v0.7.0/templates/crd/scheduling.sigs.k8s.io_elasticquotas.yaml
  versions/v0.7.0/templates/koord-descheduler-config.yaml
  versions/v0.7.0/templates/koord-scheduler-config.yaml
  versions/v0.7.0/templates/priority/koord-batch.yaml
  versions/v0.7.0/templates/priority/koord-free.yaml
  versions/v0.7.0/templates/priority/koord-mid.yaml
  versions/v0.7.0/templates/priority/koord-prod.yaml
  versions/v0.7.0/templates/rbac/koord-descheduler.yaml
  versions/v0.7.0/templates/rbac/koord-manager.yaml
  versions/v0.7.0/templates/rbac/koord-scheduler.yaml
  versions/v0.7.0/templates/rbac/koordlet.yaml
  versions/v0.7.0/templates/rbac_role.yaml
Labels: lgtm, size/XXL

#49 release v0.7.0
  charts/koordinator
  versions/v0.7.0/templates/koord-scheduler-config.yaml
Labels: lgtm, size/XS
