Repository koordinator-sh/charts, pull requests merged in 2022-08, with the labels that each got.

#31 update Reservation CRD
  versions/v0.6.0/templates/crd/scheduling.koordinator.sh_reservations.yaml
Labels: lgtm, size/XS

#34 add kubernetes config volume to koordlet
  versions/v0.6.0/templates/koordlet.yaml
Labels: lgtm, size/XS, approved

#35 release 0.6.2
  charts/koordinator
Labels: lgtm, size/XS, approved

#36 update host kubernetes volume in koordlet
  versions/v0.6.2/templates/koordlet.yaml
Labels: lgtm, size/XS, approved

#37 update koordlet.yaml in new dir v0.7.0
  versions/v0.7.0/.helmignore
  versions/v0.7.0/Chart.yaml
  versions/v0.7.0/README.md
  versions/v0.7.0/templates/_helpers.tpl
  versions/v0.7.0/templates/crd/config.koordinator.sh_clustercolocationprofiles.yaml
  versions/v0.7.0/templates/crd/scheduling.koordinator.sh_devices.yaml
  versions/v0.7.0/templates/crd/scheduling.koordinator.sh_podmigrationjobs.yaml
  versions/v0.7.0/templates/crd/scheduling.koordinator.sh_reservations.yaml
  versions/v0.7.0/templates/crd/slo.koordinator.sh_nodemetrics.yaml
  versions/v0.7.0/templates/crd/slo.koordinator.sh_nodeslos.yaml
  versions/v0.7.0/templates/crd/topology.node.k8s.io_ noderesourcetopologies.yaml
  versions/v0.7.0/templates/koord-batch.yaml
  versions/v0.7.0/templates/koord-descheduler-config.yaml
  versions/v0.7.0/templates/koord-descheduler.yaml
  versions/v0.7.0/templates/koord-free.yaml
  versions/v0.7.0/templates/koord-manager.yaml
  versions/v0.7.0/templates/koord-mid.yaml
  versions/v0.7.0/templates/koord-prod.yaml
  versions/v0.7.0/templates/koord-scheduler-config.yaml
  versions/v0.7.0/templates/koord-scheduler.yaml
  versions/v0.7.0/templates/koordlet.yaml
  versions/v0.7.0/templates/rbac_role.yaml
  versions/v0.7.0/templates/slo-controller-config.yaml
  versions/v0.7.0/templates/webhookconfiguration.yaml
  versions/v0.7.0/values.yaml
Labels: lgtm, approved, size/XXL
