Repository koordinator-sh/charts, pull requests merged in 2022-03, with the labels that each got.

#1 Initialization of koordinator charts
  .gitignore
  CONTRIBUTING.md
  LICENSE
  OWNERS
  README.md
  charts/koordinator
  scripts/lint.sh
  versions/v0.1.0/.helmignore
  versions/v0.1.0/Chart.yaml
  versions/v0.1.0/koordinator
  versions/v0.1.0/templates/NOTES.txt
  versions/v0.1.0/templates/_helpers.tpl
  versions/v0.1.0/templates/koord-controller.yaml
  versions/v0.1.0/templates/koordlet.yaml
  versions/v0.1.0/values.yaml
Labels: do-not-merge/invalid-owners-file, size/XL

#2 update image of koordlet
  versions/v0.1.0/values.yaml
Labels: lgtm, size/XS, approved

#3 update charts with koord-manager
  versions/v0.1.0/Chart.yaml
  versions/v0.1.0/koordinator
  versions/v0.1.0/templates/NOTES.txt
  versions/v0.1.0/templates/_helpers.tpl
  versions/v0.1.0/templates/config.koordinator.sh_clustercolocationprofiles.yaml
  versions/v0.1.0/templates/koord-controller.yaml
  versions/v0.1.0/templates/koord-manager.yaml
  versions/v0.1.0/templates/koordlet.yaml
  versions/v0.1.0/templates/rbac_role.yaml
  versions/v0.1.0/templates/slo-controller-config.yaml
  versions/v0.1.0/templates/slo.koordinator.sh_nodemetrics.yaml
  versions/v0.1.0/templates/webhookconfiguration.yaml
  versions/v0.1.0/values.yaml
Labels: lgtm, approved, size/XXL

#4 add resource-threshold-config
  versions/v0.1.0/templates/slo-controller-config.yaml
Labels: lgtm, size/XS, approved

#5 update ClusterColocationProfile CRD
  versions/v0.1.0/templates/config.koordinator.sh_clustercolocationprofiles.yaml
Labels: lgtm, approved, size/M

#6 add koordinator scheduler charts
  versions/v0.1.0/templates/koord-scheduler-config.yaml
  versions/v0.1.0/templates/koord-scheduler.yaml
  versions/v0.1.0/templates/rbac_role.yaml
  versions/v0.1.0/values.yaml
Labels: lgtm, approved, size/L

#7 config helm github action
  .github/configs/cr.yaml
  .github/configs/ct-install.yaml
  .github/configs/ct-lint.yaml
  .github/configs/kind-config.yaml
  .github/configs/lintconf.yaml
  .github/pull_request_template.md
  .github/semantic.yml
  .github/workflows/lint-and-test.yml
  .github/workflows/publish.yaml
  README.md
Labels: lgtm, approved, size/L

#10 fix chart release action
  .github/workflows/publish.yaml
  OWNERS
Labels: size/XS

#11 remove unused workflow step
  .github/workflows/publish.yaml
Labels: size/XS

#9 add koordinator priroity classes
  versions/v0.1.0/README.md
  versions/v0.1.0/templates/koord-batch.yaml
  versions/v0.1.0/templates/koord-free.yaml
  versions/v0.1.0/templates/koord-mid.yaml
  versions/v0.1.0/templates/koord-prod.yaml
  versions/v0.1.0/values.yaml
Labels: size/L
