Repository koordinator-sh/charts, pull requests merged in 2022-05, with the labels that each got.

#17 release v0.3.0
  charts/koordinator
  versions/v0.3.0/.helmignore
  versions/v0.3.0/Chart.yaml
  versions/v0.3.0/README.md
  versions/v0.3.0/templates/_helpers.tpl
  versions/v0.3.0/templates/config.koordinator.sh_clustercolocationprofiles.yaml
  versions/v0.3.0/templates/koord-batch.yaml
  versions/v0.3.0/templates/koord-free.yaml
  versions/v0.3.0/templates/koord-manager.yaml
  versions/v0.3.0/templates/koord-mid.yaml
  versions/v0.3.0/templates/koord-prod.yaml
  versions/v0.3.0/templates/koord-scheduler-config.yaml
  versions/v0.3.0/templates/koord-scheduler.yaml
  versions/v0.3.0/templates/koordlet.yaml
  versions/v0.3.0/templates/rbac_role.yaml
  versions/v0.3.0/templates/slo-controller-config.yaml
  versions/v0.3.0/templates/slo.koordinator.sh_nodemetrics.yaml
  versions/v0.3.0/templates/slo.koordinator.sh_nodeslos.yaml
  versions/v0.3.0/templates/webhookconfiguration.yaml
  versions/v0.3.0/values.yaml
Labels: lgtm, approved, size/XXL

#18 add new release for v0.3.1
  charts/koordinator
  versions/v0.3.1/.helmignore
  versions/v0.3.1/Chart.yaml
  versions/v0.3.1/README.md
  versions/v0.3.1/templates/_helpers.tpl
  versions/v0.3.1/templates/config.koordinator.sh_clustercolocationprofiles.yaml
  versions/v0.3.1/templates/koord-batch.yaml
  versions/v0.3.1/templates/koord-free.yaml
  versions/v0.3.1/templates/koord-manager.yaml
  versions/v0.3.1/templates/koord-mid.yaml
  versions/v0.3.1/templates/koord-prod.yaml
  versions/v0.3.1/templates/koord-scheduler-config.yaml
  versions/v0.3.1/templates/koord-scheduler.yaml
  versions/v0.3.1/templates/koordlet.yaml
  versions/v0.3.1/templates/rbac_role.yaml
  versions/v0.3.1/templates/slo-controller-config.yaml
  versions/v0.3.1/templates/slo.koordinator.sh_nodemetrics.yaml
  versions/v0.3.1/templates/slo.koordinator.sh_nodeslos.yaml
  versions/v0.3.1/templates/webhookconfiguration.yaml
  versions/v0.3.1/values.yaml
Labels: lgtm, approved, size/XXL

#19 update koord-scheduler rbac and configuration
  versions/v0.4.0/.helmignore
  versions/v0.4.0/Chart.yaml
  versions/v0.4.0/README.md
  versions/v0.4.0/templates/_helpers.tpl
  versions/v0.4.0/templates/config.koordinator.sh_clustercolocationprofiles.yaml
  versions/v0.4.0/templates/koord-batch.yaml
  versions/v0.4.0/templates/koord-free.yaml
  versions/v0.4.0/templates/koord-manager.yaml
  versions/v0.4.0/templates/koord-mid.yaml
  versions/v0.4.0/templates/koord-prod.yaml
  versions/v0.4.0/templates/koord-scheduler-config.yaml
  versions/v0.4.0/templates/koord-scheduler.yaml
  versions/v0.4.0/templates/koordlet.yaml
  versions/v0.4.0/templates/rbac_role.yaml
  versions/v0.4.0/templates/slo-controller-config.yaml
  versions/v0.4.0/templates/slo.koordinator.sh_nodemetrics.yaml
  versions/v0.4.0/templates/slo.koordinator.sh_nodeslos.yaml
  versions/v0.4.0/templates/webhookconfiguration.yaml
  versions/v0.4.0/values.yaml
Labels: lgtm, approved, size/XXL

#20 add koordlet unix socket file in /var/run/koordlet/
  versions/v0.4.0/templates/koordlet.yaml
Labels: lgtm, approved, size/S

#21 release v0.4.0
  charts/koordinator
  versions/v0.4.0/templates/rbac_role.yaml
  versions/v0.4.0/values.yaml
Labels: lgtm, size/XS, approved

#22 update chart version to v0.4.0
  versions/v0.4.0/Chart.yaml
Labels: lgtm, size/XS, approved
