Repository koordinator-sh/charts, pull requests merged in 2022-06, with the labels that each got.

#23 feat: add node proxy rbac
  versions/v0.4.0/templates/rbac_role.yaml
Labels: lgtm, size/XS, approved

#25 prepare release v0.5.0
  versions/v0.5.0/.helmignore
  versions/v0.5.0/Chart.yaml
  versions/v0.5.0/README.md
  versions/v0.5.0/templates/_helpers.tpl
  versions/v0.5.0/templates/config.koordinator.sh_clustercolocationprofiles.yaml
  versions/v0.5.0/templates/koord-batch.yaml
  versions/v0.5.0/templates/koord-free.yaml
  versions/v0.5.0/templates/koord-manager.yaml
  versions/v0.5.0/templates/koord-mid.yaml
  versions/v0.5.0/templates/koord-prod.yaml
  versions/v0.5.0/templates/koord-scheduler-config.yaml
  versions/v0.5.0/templates/koord-scheduler.yaml
  versions/v0.5.0/templates/koordlet.yaml
  versions/v0.5.0/templates/rbac_role.yaml
  versions/v0.5.0/templates/slo-controller-config.yaml
  versions/v0.5.0/templates/slo.koordinator.sh_nodemetrics.yaml
  versions/v0.5.0/templates/slo.koordinator.sh_nodeslos.yaml
  versions/v0.5.0/templates/webhookconfiguration.yaml
  versions/v0.5.0/values.yaml
Labels: lgtm, approved, size/XXL

#26 update scheduler config, deployment and crd
  versions/v0.5.0/templates/koord-scheduler-config.yaml
  versions/v0.5.0/templates/koord-scheduler.yaml
  versions/v0.5.0/templates/rbac_role.yaml
  versions/v0.5.0/templates/topology.node.k8s.io_ noderesourcetopologies.yaml
  versions/v0.5.0/values.yaml
Labels: lgtm, approved, size/L

#27 release v0.5.0
  versions/v0.5.0/README.md
  versions/v0.5.0/templates/koord-manager.yaml
  versions/v0.5.0/templates/koord-scheduler.yaml
  versions/v0.5.0/templates/koordlet.yaml
  versions/v0.5.0/values.yaml
Labels: lgtm, approved, size/M

#28 update symbolic link
  charts/koordinator
Labels: lgtm, size/XS, approved
