Repository koordinator-sh/charts, pull requests merged in 2023-08, with the labels that each got.

#66 Add chart v1.3.0
  versions/v1.3.0/.helmignore
  versions/v1.3.0/Chart.yaml
  versions/v1.3.0/README.md
  versions/v1.3.0/templates/_helpers.tpl
  versions/v1.3.0/templates/crd/config.koordinator.sh_clustercolocationprofiles.yaml
  versions/v1.3.0/templates/crd/scheduling.koordinator.sh_devices.yaml
  versions/v1.3.0/templates/crd/scheduling.koordinator.sh_podmigrationjobs.yaml
  versions/v1.3.0/templates/crd/scheduling.koordinator.sh_reservations.yaml
  versions/v1.3.0/templates/crd/scheduling.sigs.k8s.io_elasticquotas.yaml
  versions/v1.3.0/templates/crd/scheduling.sigs.k8s.io_podgroups.yaml
  versions/v1.3.0/templates/crd/slo.koordinator.sh_nodemetrics.yaml
  versions/v1.3.0/templates/crd/slo.koordinator.sh_nodeslos.yaml
  versions/v1.3.0/templates/crd/topology.node.k8s.io_noderesourcetopologies.yaml
  versions/v1.3.0/templates/koord-descheduler-config.yaml
  versions/v1.3.0/templates/koord-descheduler.yaml
  versions/v1.3.0/templates/koord-manager.yaml
  versions/v1.3.0/templates/koord-scheduler-config.yaml
  versions/v1.3.0/templates/koord-scheduler.yaml
  versions/v1.3.0/templates/koordlet-service.yaml
  versions/v1.3.0/templates/koordlet-servicemonitor.yaml
  versions/v1.3.0/templates/koordlet.yaml
  versions/v1.3.0/templates/priority/koord-batch.yaml
  versions/v1.3.0/templates/priority/koord-free.yaml
  versions/v1.3.0/templates/priority/koord-mid.yaml
  versions/v1.3.0/templates/priority/koord-prod.yaml
  versions/v1.3.0/templates/rbac/koord-descheduler.yaml
  versions/v1.3.0/templates/rbac/koord-manager.yaml
  versions/v1.3.0/templates/rbac/koord-scheduler.yaml
  versions/v1.3.0/templates/rbac/koordlet.yaml
  versions/v1.3.0/templates/slo-controller-config.yaml
  versions/v1.3.0/templates/webhookconfiguration.yaml
  versions/v1.3.0/values.yaml
Labels: lgtm, approved, size/XXL

#68 update scheduler config and deployment
  versions/v1.3.0/templates/koord-scheduler-config.yaml
  versions/v1.3.0/templates/koord-scheduler.yaml
  versions/v1.3.0/values.yaml
Labels: lgtm, approved, size/S

#67 Update chart v1.3.0
  versions/v1.3.0/templates/koordlet.yaml
  versions/v1.3.0/values.yaml
Labels: lgtm, size/XS
