Repository koordinator-sh/charts, pull requests merged in 2024-06, with the labels that each got.

#89 Add chart v1.5.0
  versions/v1.5.0/.helmignore
  versions/v1.5.0/Chart.yaml
  versions/v1.5.0/README.md
  versions/v1.5.0/templates/_helpers.tpl
  versions/v1.5.0/templates/crd/analysis.koordinator.sh_recommendations.yaml
  versions/v1.5.0/templates/crd/config.koordinator.sh_clustercolocationprofiles.yaml
  versions/v1.5.0/templates/crd/quota.koordinator.sh_elasticquotaprofiles.yaml
  versions/v1.5.0/templates/crd/scheduling.koordinator.sh_devices.yaml
  versions/v1.5.0/templates/crd/scheduling.koordinator.sh_podmigrationjobs.yaml
  versions/v1.5.0/templates/crd/scheduling.koordinator.sh_reservations.yaml
  versions/v1.5.0/templates/crd/scheduling.sigs.k8s.io_elasticquotas.yaml
  versions/v1.5.0/templates/crd/scheduling.sigs.k8s.io_podgroups.yaml
  versions/v1.5.0/templates/crd/slo.koordinator.sh_nodemetrics.yaml
  versions/v1.5.0/templates/crd/slo.koordinator.sh_nodeslos.yaml
  versions/v1.5.0/templates/crd/topology.node.k8s.io_noderesourcetopologies.yaml
  versions/v1.5.0/templates/koord-descheduler-config.yaml
  versions/v1.5.0/templates/koord-descheduler.yaml
  versions/v1.5.0/templates/koord-manager.yaml
  versions/v1.5.0/templates/koord-scheduler-config.yaml
  versions/v1.5.0/templates/koord-scheduler.yaml
  versions/v1.5.0/templates/koordlet-service.yaml
  versions/v1.5.0/templates/koordlet-servicemonitor.yaml
  versions/v1.5.0/templates/koordlet.yaml
  versions/v1.5.0/templates/priority/koord-batch.yaml
  versions/v1.5.0/templates/priority/koord-free.yaml
  versions/v1.5.0/templates/priority/koord-mid.yaml
  versions/v1.5.0/templates/priority/koord-prod.yaml
  versions/v1.5.0/templates/rbac/koord-descheduler.yaml
  versions/v1.5.0/templates/rbac/koord-manager.yaml
  versions/v1.5.0/templates/rbac/koord-scheduler.yaml
  versions/v1.5.0/templates/rbac/koordlet.yaml
  versions/v1.5.0/templates/slo-controller-config.yaml
  versions/v1.5.0/templates/webhookconfiguration.yaml
  versions/v1.5.0/values.yaml
Labels: lgtm, approved, size/XXL

#90 Add chart v1.5.0 link and update OWNERS
  OWNERS
  charts/koordinator
  scripts/lint.sh
Labels: lgtm, size/XS, approved

#88 support TerwayQoS feature
  versions/v1.4.1/templates/koordlet.yaml
Labels: lgtm, approved, size/S
